export const servicesCards = (t) => [
    {
        title:t("services.listing.one.title"),
        desc:t("services.listing.one.desc"),
        number:t("services.listing.one.count"),
        colorScheme:"purpleOrange",
        imageClass:"webAppImage",
        path:"web-development",
         footer:"services_heading"
    },
    {
        title:t("services.listing.two.title"),
        desc:t("services.listing.two.desc"),
        number:t("services.listing.two.count"),
        colorScheme:"whiteOrange",
        imageClass:"inner-one",
         path:"software-development",
         footer:"footer_services_heading"
    },
    {
        title:t("services.listing.three.title"),
        desc:t("services.listing.three.desc"),
        number:t("services.listing.three.count"),
        colorScheme:"whiteOrange",
        imageClass:"mobileAppImage",
         path:"mobile-development",
          footer:"footer_services_heading"
    },
    {
        title:t("services.listing.four.title"),
        desc:t("services.listing.four.desc"),
        number:t("services.listing.four.count"),
        colorScheme:"purpleOrange",
        imageClass:"inner-two",
         path:"graphics-design",
          footer:"footer_services_heading"
    },
    {
        title:t("services.listing.five.title"),
        desc:t("services.listing.five.desc"),
        number:t("services.listing.five.count"),
        colorScheme:"purpleOrange",
        imageClass:"inner-one",
         path:"cloud-computing",
          footer:"footer_services_heading"
    },
    {
        title:t("services.listing.six.title"),
        desc:t("services.listing.six.desc"),
        number:t("services.listing.six.count"),
        colorScheme:"whiteOrange",
        imageClass:"inner-two",
         path:"ui-ux",
          footer:"footer_services_heading"
    },
    {
        title:t("services.listing.seven.title"),
        desc:t("services.listing.seven.desc"),
        number:t("services.listing.seven.count"),
        colorScheme:"whiteOrange",
        imageClass:"qaImage",
         path:"quality-assurance"
    },
    {
        title:t("services.listing.eight.title"),
        desc:t("services.listing.eight.desc"),
        number:t("services.listing.eight.count"),
        colorScheme:"purpleOrange",
        imageClass:"inner-two",
         path:"quality-assurance"
    },
]